repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: 'https://github.com/psf/black'
    rev: 24.2.0
    hooks:
      - id: black
  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.0.0
    hooks:
      - id: flake8
  - repo: 'https://github.com/FeryET/pre-commit-rust'
    rev: v1.0.2   # cannot make 1.0.3 work
    hooks:
      - id: fmt
        args: ["--verbose", "--"]
      - id: cargo-check
